name: Compile Hugo and Push to Gh-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository and fetch submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: true
          fetch-depth: 0      

      # 2. Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      # 3. Build the Hugo site
      - name: Build site
        run: hugo --minify -d docs

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
          publish_dir: ./docs
          publish_branch: gh-pages
          keep_files: false


